use magic mount if mount overlayfs fails

diff --git a/initrd/scripts/4-magisk b/initrd/scripts/4-magisk
--- a/initrd/scripts/4-magisk
+++ b/initrd/scripts/4-magisk
@@ -65,8 +65,8 @@ cp -a /magisk/* /android/magisk
 cat /magisk/init.kokoro.rc >>/android/init.rc
 else
 sysblock="$(mount | grep " /android " | tail -1 | awk '{ print $1 }')"
-mkdir /system_root
-mount $sysblock /system_root
+mkdir /dev/system_root
+mount $sysblock /dev/system_root
 # prepare for second stage
 chmod 750 $inittmp
 mount -t overlay tmpfs -o lowerdir=/android/system/etc/init,upperdir=$inittmp/.overlay/upper,workdir=$inittmp/.overlay/work /android/system/etc/init
@@ -74,6 +74,36 @@ sed -i "s|MAGISK_FILES_BASE|/system/etc/init/magisk|g" /magisk/overlay.sh
 sed -i "s|MAGISK_FILES_BASE|/system/etc/init/magisk|g" /magisk/init.kokoro.rc
 cp -a /magisk $inittmp/.overlay/upper
 cp /magisk/init.kokoro.rc $inittmp/.overlay/upper/init.kokoro.rc
+fi
+
+# fail back to magic mount if overlayfs is unavailable
+
+if ! mount -t overlay | grep -q " /android/system/etc/init "; then
+  mount -t tmpfs tmpfs -o mode=0755 /android/system/etc/init
+  for file in $(ls /android/dev/system_root/system/etc/init); do
+    (
+        sfile="/android/dev/system_root/system/etc/init/$file"
+        xfile="/android/system/etc/init/$file"
+        if [ -L "$sfile" ]; then
+            cp "$sfile" "$xfile"
+        elif [ -d "$sfile" ]; then
+            mkdir "$xfile"
+            mount --bind "$sfile" "$xfile"
+        else
+            echo -n >"$xfile"
+            mount --bind "$sfile" "$xfile"
+        fi
+     ) &
+  done
+  sleep 0.05
+  umount -l /android/system/etc/init/magisk
+  umount -l /android/system/etc/init/magisk.rc
+  rm -rf /android/system/etc/init/magisk
+  rm -rf /android/system/etc/init/magisk.rc
+  mkdir /android/system/etc/init/magisk
+  mount --bind $inittmp/.overlay/upper/magisk /android/system/etc/init/magisk
+  echo -n >/android/system/etc/init/magisk.rc
+  mount --bind $inittmp/.overlay/upper/magisk.rc /android/system/etc/init/magisk.rc
 fi
 
 # pre-init sepolicy patch
